### ISSUE TITLE
Migrations not being created for models

### ISSUE THREAD

**Issue by nam20485** [hackoregon/2019-backend-cookiecutter-django#9]
I have some models defined and being served via some endpoints I created in my sub_project Django application. The docker-entrypoint.sh script runs the makemigrations and migrate commands when the image is started via the start.sh -d command. However it is not picking up on the new models and creating migrations for them. 

I don't know if it is something I am doing, or just because of the new structure we have in this architecture where we have the Django app separated from the Django project that runs in the docker backend.

Have you been able to create a model and have the migrations pick up on it create?

**Comment by bhgrant8** [comment]
Unless there is a potential issue with the pathing, the django project and django app should essentially be in the same container/environment within the docker container, so should be able to communicate together.

You should be able to open an interactive shell with `docker exec -it <container_name> bin/bash`
in a new terminal window, while project is running. Perhaps doing this and attempting to run the migrations manually from within the container could help shed some light.

I'll see what I can investigate as well

**Comment by bhgrant8** [comment]
@nam20485 , I think this maybe solved with the same fix as #12, could you attempt to update:

https://github.com/hackoregon/2019-sandbox-backend/blob/73dda9f3a7ed031bcd69565e87c90138c4e89e9b/local_settings/settings.py#L25

to just be `api` based on the app name in this file:

https://github.com/hackoregon/2019-sandbox-backend/blob/73dda9f3a7ed031bcd69565e87c90138c4e89e9b/hackoregon_sandbox/api/apps.py#L5]]

Have a commit to fix in template

**Comment by bhgrant8** [comment]
@nam20485, closing for lack of response, if this is still an issue, please re-open

**Comment by nam20485** [comment]
I have modified the line as suggested. 

https://github.com/hackoregon/2019-sandbox-backend/blob/deacbc52610c1db9085900e254efaa46aad63720/local_settings/settings.py#L25

This did solve one issue I was having (same one Jeff Beyer reported `RuntimeError: Model class toad.models.BusAllStops doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`)

But I am still unable to create any migrations.

Have any of you been able to create a migration successfully?

**Comment by bhgrant8** [comment]
@nam20485 

when you say unable to create migrations, where specifically is the process failing? what are the specific steps you are taking?

do you just never see migrations created, w/o any error messages? or something else? 

what happens when you run the "makemigrations" command within the docker container with the exec command?

i created the bug report template after this issue was open but could you provide the following:

```
*Provide logs, screenshots, or other indicators of the issue. Any error messages/logs should be included in a formatted code block. Please only provide screenshots when visual information is useful. (NO SCREENSHOTS OF CODE)*
```

**Comment by nam20485** [comment]
OK sorry I know- I will create a better issue with the template that provides the necessary details that you need to better attack this.

**Comment by bhgrant8** [comment]
Thanks, and nothing to be sorry about

**Comment by nam20485** [comment]
OK I created a new one with all the info I know so far :)

#26

**Comment by nam20485** [comment]
Replaced by #26- closing out.
